# -*- coding: utf-8 -*-
"""Week5_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11qTrFloxSa_V1xncFk6NzBbaCj92s5pV
"""

# Question 1
# Inheritence

# define your class
class firms:
  # many attributes for this class
  def __init__(self, name_client, year, services):
    self.name_client  = name_client
    self.year = year
    self.services = services
# create a sub class
class department(firms):
  pass

# create an object
audit = department("World_Bank", "2014", ("Advisory", "Tax", "Legal"))
print(audit.name_client)

# Question 2
# Polymorphism Challenge

class Vehicles:
  def move(self):
    return "Bentley"

class Bike:
  def move(self):
    return "Kawasaki"

for person in [Vehicles(), Bike()] :
  print(person.move())